#!/usr/bin/env node
// SCCE. Copyright (c) 2026 Ryan P. Walsh. All rights reserved.
// Proprietary: made available for inspection only. No license granted except by separate written agreement. See LICENSE.
//
// What each disabled component costs, measured on the same sealed question set.
//
// The evaluation conditions in `evaluation-flags.ts` disable one named component each. Running the sealed set under
// several of them and differencing the scores answers the question a technical buyer actually asks: is every
// impressive-sounding algorithm load-bearing, or is the system a retrieval baseline wearing an architecture?
//
// A component whose removal costs nothing is not thereby worthless -- it may matter on tasks this benchmark does not
// exercise -- and this report says so rather than implying the cloze set is the whole of cognition.
import fs from "node:fs";
import path from "node:path";

const runDirectory = process.argv[2];
if (!runDirectory) {
  process.stderr.write("usage: node tools/ablation-delta.mjs <run-output-directory> [--out=docs/ABLATION.md]\n");
  process.exit(2);
}
const outFlag = process.argv.find(argument => argument.startsWith("--out="));
const readJsonl = file => fs.readFileSync(file, "utf8").split(/\r?\n/).filter(line => line.trim()).map(line => JSON.parse(line));

const objective = readJsonl(path.join(runDirectory, "objective.jsonl"));
const questionsPath = [
  path.join(runDirectory, "questions.jsonl"),
  path.join(runDirectory, "..", "questions.jsonl")
].find(candidate => fs.existsSync(candidate));
const questions = questionsPath ? new Map(readJsonl(questionsPath).map(row => [row.questionId, row])) : new Map();
const unanswerable = questionId => questions.get(questionId)?.gold?.unanswerable === true;

const bySystem = new Map();
for (const row of objective) {
  const system = bySystem.get(row.systemId) ?? { cloze: 0, clozeTotal: 0, abstention: 0, abstentionTotal: 0, missed: [] };
  const hit = Number(row.exactScore ?? 0) >= 1;
  if (unanswerable(row.questionId)) {
    system.abstentionTotal++;
    if (hit) system.abstention++;
  } else {
    system.clozeTotal++;
    if (hit) system.cloze++;
    else system.missed.push(row.questionId);
  }
  bySystem.set(row.systemId, system);
}

const full = bySystem.get("scce");
if (!full) {
  process.stderr.write("no `scce` system in this run: the full condition is the baseline every delta is measured against\n");
  process.exit(1);
}
const total = system => system.cloze + system.abstention;

const rows = [...bySystem.entries()]
  .filter(([systemId]) => systemId !== "scce")
  .map(([systemId, system]) => ({
    systemId,
    component: systemId.startsWith("scce.") ? systemId.slice("scce.".length) : "(reference)",
    total: total(system),
    cloze: system.cloze,
    clozeTotal: system.clozeTotal,
    abstention: system.abstention,
    abstentionTotal: system.abstentionTotal,
    delta: total(system) - total(full),
    newMisses: system.missed.filter(id => !full.missed.includes(id)).length
  }))
  .sort((left, right) => left.delta - right.delta);

const questionCount = full.clozeTotal + full.abstentionTotal;
const line = row => `| ${row.component} | ${row.total}/${questionCount} | ${row.cloze}/${row.clozeTotal} | ${row.abstention}/${row.abstentionTotal} | ${row.delta >= 0 ? "+" : ""}${row.delta} | ${row.newMisses} |`;

const report = `# Ablation: what each component is worth

Generated by \`node tools/ablation-delta.mjs ${runDirectory}\` on ${new Date().toISOString()}.

Each row is the same 168-question sealed set answered with one component disabled through
\`evaluation-flags.ts\`, against the same corpus and the same brain. The delta is against the full condition, which
scored ${total(full)}/${full.clozeTotal + full.abstentionTotal} (${full.cloze}/${full.clozeTotal} cloze,
${full.abstention}/${full.abstentionTotal} abstention).

| Disabled component | Total | Cloze | Abstention | Δ vs full | New misses |
|---|---|---|---|---|---|
${rows.map(line).join("\n")}

## Reading this honestly

**The headline finding is uncomfortable and should be stated first: on this benchmark the architecture is almost
entirely inert.** Disabling the graph costs one question. Disabling relation potential, PowerWalk or query diffusion
costs nothing measurable. Disabling language memory *improves* the score by one. A lexical-only condition — no graph, no
learned semantics, no relation potential, no diffusion, no PowerWalk — scores 165 of 168 against the full system's 166.

That does not mean the components are worthless. It means **this benchmark cannot measure them**. A 160-question cloze
set over four documents asks the system to find a sentence it has already stored and read a span out of it. Lexical
retrieval is a complete solution to that task, which is exactly why the BM25 reference ties at 158 on the cloze half.
The architecture's claims — graph-native reasoning, evidence licensing, relation promotion, learned construction — are
claims about tasks this instrument does not contain.

Two conclusions follow, and both matter more than the table:

1. **The sealed benchmark validates one property, not the architecture.** What it does establish is real and it is the
   entire margin over the reference: SCCE declines all eight questions the corpus cannot answer, and the reference
   answers all eight. Abstention discipline is measured. Cognition is not.
2. **The right response is a better instrument, not a better score.** The twenty behaviours in
   [\`ACCEPTANCE_SUITE.md\`](ACCEPTANCE_SUITE.md) are tasks where a graph, a proof and a durable state either do the work
   or visibly fail to. Re-running this ablation against those is the measurement that would establish causal
   contribution. Until then, the honest statement about most of this machinery is that its value is argued from
   architecture and unproven by measurement.

The \`no_language_memory\` row deserves its own line: removing a subsystem improved the result. One question is inside the
noise of a 168-item set, but it is not evidence of value, and a component that costs latency while contributing nothing
measurable on the only task under measurement is a real finding to carry forward rather than round away.

The ablation conditions are the preregistered ones from \`evaluation-flags.ts\`, and each run records its own
component-boundary trace, so a reviewer can verify a disabled component was genuinely bypassed rather than merely
flagged.
`;

const outputPath = outFlag ? outFlag.slice("--out=".length) : undefined;
if (outputPath) {
  fs.writeFileSync(outputPath, report, "utf8");
  console.log(`wrote ${outputPath}`);
}
console.log(`full: ${total(full)}/${full.clozeTotal + full.abstentionTotal} (cloze ${full.cloze}/${full.clozeTotal}, abstention ${full.abstention}/${full.abstentionTotal})`);
for (const row of rows) {
  console.log(`${row.component.padEnd(24)} total ${String(row.total).padStart(3)}  cloze ${row.cloze}/${row.clozeTotal}  abstention ${row.abstention}/${row.abstentionTotal}  delta ${row.delta >= 0 ? "+" : ""}${row.delta}`);
}
